---
title: "data_import"
author: "Fang Wang"
date: "2024-09-17"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, message = FALSE}
setwd("/Users/fangwang/Downloads/P8105 Data Science I/Lecture 5")
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to import data.

## Import the dataset and clean the names:
```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df) # change variables' names
```

### Look at the dataset:
```{r}
head(litters_df)
tail(litters_df, 10)
```

```{r eval = FALSE}
view(litters_df)
```

## Import FAS Pups:
```{r}
pups_df = read_csv(file = "./data/FAS_pups.csv") # difference "."???
pups_df = janitor::clean_names(pups_df)
pups_df
```

## Look at read_csv options:

```{r}
litters_df =
  read_csv("./data/FAS_pups.csv",
  col_names = TRUE,
  skip = 2)
```

## What about missing data:
```{r}
litters_df =
  read_csv(
    file = "data/FAS_litters.csv",,
    na = c("NA" ,"", ".") #!!!how to insert the NA items.
  )
litters_df = janitor::clean_names(litters_df)
pull(litters_df, gd0_weight) # pull() is a new function
```

## What if we code "group" as a factor variable?
```{r}
litters_df =
  read_csv =(
    file = ".data/FAS_litters.csv",,
    na = c("NA", ".", ""),
    col_types = cols(
    Group = col_factor() #??change the variable to factor vector
    )
  )
```


## Import an excel file:
```{r}
mlb_df = read_excel("data/mlb11.xlsx", sheet = "mlb11")
```

## Import an SAS data:

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


## Never use read.csv()??: R basic
```{r}
litters_df = read.csv("data/FAS_litters.csv")
litters_df$L # don't use "$" sign in the code??
```

# solve git connection